steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/STRONG-PROVINCE-463111-J9/mm-mirror-repo/mm-mirror:latest
      - -t
      - europe-west1-docker.pkg.dev/STRONG-PROVINCE-463111-J9/mm-mirror-repo/mm-mirror:${SHORT_SHA}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/STRONG-PROVINCE-463111-J9/mm-mirror-repo/mm-mirror:latest
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/STRONG-PROVINCE-463111-J9/mm-mirror-repo/mm-mirror:${SHORT_SHA}
