# Собираем и пушим образ в Artifact Registry
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "europe-west1-docker.pkg.dev/strong-province-463111-j9/mm-mirror-repo/mm-mirror:latest", "-f", "Dockerfile", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "europe-west1-docker.pkg.dev/strong-province-463111-j9/mm-mirror-repo/mm-mirror:latest"]

# Куда писать логи (важно для ошибки, которую вы видели)
options:
  logging: CLOUD_LOGGING_ONLY

# Каким сервис‑аккаунтом выполнять сборку
serviceAccount: "projects/strong-province-463111-j9/serviceAccounts/mm-mirror-483hdsk@strong-province-463111-j9.iam.gserviceaccount.com"

# Чтобы образ был виден в истории сборок
images:
  - "europe-west1-docker.pkg.dev/strong-province-463111-j9/mm-mirror-repo/mm-mirror:latest"
